# Generated by Django 4.2 on 2025-05-06 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtimebillpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airtime_bill_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankdeposit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashpowerbillpayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_power_bill_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomingmoney',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_money', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internetbundlepurchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internet_bundle_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttocodeholder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_to_code_holder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thirdpartytransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_party_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfertomobile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to_mobile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voicebundlepurchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voice_bundle_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalfromagent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals_from_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
